me    'puppet-magentoce'
version '0.1.0'
source 'UNKNOWN'
author 'BjoernSchotte'
license 'GPL v3 or later'
summary 'Magento CE Development Environment'
description 'Setup Magento CE with MySQL and Apache via puppet'
project_page 'http://www.magentocommerce.com/svn'
